# -*- coding: utf-8 -*-
"""qGGGGGGG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17dftmK1sE59lo0jXPUUcSYpqUUnSTmLa
"""

valor = int(input())
n = 1

while valor != -1:
    s = 0

    if valor == 0:
      s = 4
    else:
      s = valor * (4 * valor) + (valor*4) + 1


    print('Caso',n)
    print(s)
    print('')

    n = n+1
    valor = int(input())